(define (problem FR_1_9)
 (:domain first-response)
 (:objects  l1  - location
	    f1 - fire_unit
	    v1 v2 v3 v4 v5 v6 v7 v8 v9 - victim
	    m1 - medical_unit
)
 (:init 
	;;strategic locations
     (hospital l1)
     (water-at l1)
	;;disaster info
     (fire l1)
     (victim-at v1 l1)
     (victim-status v1 hurt)
     (fire l1)
     (victim-at v2 l1)
     (victim-status v2 hurt)
     (fire l1)
     (victim-at v3 l1)
     (victim-status v3 dying)
     (fire l1)
     (victim-at v4 l1)
     (victim-status v4 dying)
     (fire l1)
     (victim-at v5 l1)
     (victim-status v5 hurt)
     (fire l1)
     (victim-at v6 l1)
     (victim-status v6 hurt)
     (fire l1)
     (victim-at v7 l1)
     (victim-status v7 dying)
     (fire l1)
     (victim-at v8 l1)
     (victim-status v8 dying)
     (fire l1)
     (victim-at v9 l1)
     (victim-status v9 hurt)
	;;map info
	(adjacent l1 l1)
	(fire-unit-at f1 l1)
	(medical-unit-at m1 l1)
	
   (= (total-cost) 0)
   )
  (:utility
     (= (nfire l1) 40)
     (= (victim-status v1 healthy) 14)
     (= (victim-status v2 healthy) 5)
     (= (victim-status v3 healthy) 31)
     (= (victim-status v4 healthy) 34)
     (= (victim-status v5 healthy) 12)
     (= (victim-status v6 healthy) 15)
     (= (victim-status v7 healthy) 25)
     (= (victim-status v8 healthy) 49)
     (= (victim-status v9 healthy) 50)
 )
 
(:bound 5)
)
