(define (problem bw_5_1)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b3) (on b2 b1) (on-table b3) (on-table b4) (on b5 b4) (clear b2) (clear b5)
    (= (total-cost) 0)
    )
    (:utility
      (= (emptyhand) 33)
      (= (on b1 b2) 5)
      (= (on b2 b5) 19)
      (= (on-table b3) 44)
      (= (on-table b4) 10)
      (= (on-table b5) 26)
      (= (clear b1) 13)
      (= (clear b3) 23)
      (= (clear b4) 33)
  )

(:bound 5)
)
