(define (problem bw_5_2)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on-table b1) (on-table b2) (on-table b3) (on b4 b2) (on b5 b1) (clear b3) (clear b4) (clear b5)
    (= (total-cost) 0)
    )
    (:utility
      (= (emptyhand) 33)
      (= (on-table b1) 36)
      (= (on-table b2) 25)
      (= (on-table b3) 12)
      (= (on b4 b1) 11)
      (= (on b5 b2) 23)
      (= (clear b3) 12)
      (= (clear b4) 2)
      (= (clear b5) 18)
  )

(:bound 3)
)
