(define (problem bw_5_6)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on-table b1) (on b2 b4) (on b3 b2) (on-table b4) (on-table b5) (clear b1) (clear b3) (clear b5)
    (= (total-cost) 0)
    )
    (:utility
      (= (emptyhand) 33)
      (= (on-table b1) 14)
      (= (on b2 b4) 11)
      (= (on-table b3) 38)
      (= (on b4 b3) 40)
      (= (on b5 b1) 32)
      (= (clear b2) 6)
      (= (clear b5) 49)
  )

(:bound 6)
)
