(define (problem bw_5_5)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on-table b1) (on-table b2) (on b3 b5) (on b4 b2) (on b5 b1) (clear b3) (clear b4)
    (= (total-cost) 0)
    )
    (:utility
      (= (emptyhand) 42)
      (= (on b1 b3) 10)
      (= (on b2 b4) 27)
      (= (on-table b3) 31)
      (= (on b4 b1) 23)
      (= (on-table b5) 38)
      (= (clear b2) 23)
      (= (clear b5) 33)
  )

(:bound 4)
)
