(define (problem bw_5_8)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b2) (on b2 b4) (on b3 b1) (on b4 b5) (on-table b5) (clear b3)
    (= (total-cost) 0)
    )
    (:utility
      (= (emptyhand) 32)
      (= (on-table b1) 45)
      (= (on-table b2) 26)
      (= (on b3 b2) 6)
      (= (on b4 b3) 5)
      (= (on b5 b4) 21)
      (= (clear b1) 41)
      (= (clear b5) 49)
  )

(:bound 4)
)
