(define (problem bw_5_3)
  (:domain blocks-domain)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on-table b1) (on b2 b1) (on b3 b2) (on b4 b5) (on-table b5) (clear b3) (clear b4)
    (= (total-cost) 0)
    )
    (:utility
      (= (emptyhand) 31)
      (= (on-table b1) 36)
      (= (on-table b2) 23)
      (= (on b3 b1) 41)
      (= (on-table b4) 41)
      (= (on b5 b3) 34)
      (= (clear b2) 19)
      (= (clear b4) 38)
      (= (clear b5) 28)
  )

(:bound 1)
)
